version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  spring-server:
    image: kun368/vote-dapp:master
    restart: always
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    links:
      - db
